name: misana_finance_app
description: "Misana Finance mobile app (Auth + KYC via Express Gateway)"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  smooth_page_indicator: ^1.0.0
  shared_preferences: ^2.0.15
  flutter_svg: ^2.1.6
  socket_io_client: ^2.0.0
  curved_navigation_bar: ^1.0.3
  flutterwave_standard: ^1.1.0
  equatable: ^2.0.5
  dio: ^5.5.0+1
  intl: ^0.20.2
  lottie: ^3.1.2
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.10
  image_picker:
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/orange.svg
    - assets/images/orange.png
    - assets/loader.svg
    - assets/loading.json
    - assets/illustrations/

flutter_native_splash:
  color: "#FF6B35"
  image: assets/images/misana_orange.png
  color_dark: "#FF6B35"
  image_dark: assets/images/misana_white.png
  android_12:
    image: assets/images/misana_orange.png
    color: "#FF6B35"
    image_dark: assets/images/misana_white.png
    color_dark: "#FF6B35"
  web: false